services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: studybud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studybud"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    image: 637417025050.dkr.ecr.ap-southeast-2.amazonaws.com/studybud-web:latest
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data:
